// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsqAmEe81KXNeJS3pH-3GUH_ENdyGrbqE',
    appId: '1:499231534361:web:c615800d465d601808e988',
    messagingSenderId: '499231534361',
    projectId: 'moneymate-658a1',
    authDomain: 'moneymate-658a1.firebaseapp.com',
    storageBucket: 'moneymate-658a1.firebasestorage.app',
    measurementId: 'G-5C8818CXDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALx966EyeMXBdH65_F0S-QWPwqaAkG5mg',
    appId: '1:499231534361:android:6b9f0b70369ed11908e988',
    messagingSenderId: '499231534361',
    projectId: 'moneymate-658a1',
    storageBucket: 'moneymate-658a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNL-csHUSgFXRhnh5vwTtnfAv-ACAKT7w',
    appId: '1:499231534361:ios:91e51cbd1dc68f9208e988',
    messagingSenderId: '499231534361',
    projectId: 'moneymate-658a1',
    storageBucket: 'moneymate-658a1.firebasestorage.app',
    iosBundleId: 'com.example.moneymate',
  );
}
